# Site settings
title: David Rappaport
email: david@rappaport.me
description: "Student at CU Boulder. Making cool things with wires."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4d6b92 #80B3FF
  secondary: 1A3A62 #FD6E8A
  secondary-dark: 082345 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/david-rappaport/2b/282/916
  - title: file-text-o
    url: http://davidrappaport.wixsite.com/portfolio
# Postal address (add as many lines as necessary)
address:
  - line: 530.304.7958

# Build settings
markdown: kramdown
permalink: pretty
